name: calc
version: 0.1.0
description: Calculations for Dart developers. Tensors / vectors / matrices, probability
  distributions, and more.
homepage: https://github.com/dint-dev/calc

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  collection: ^1.15.0
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0